### ISSUE TITLE
Can't find the "mod menu"

### ISSUE THREAD

**Issue by SirFireball3521** [kyrptonaught/CMDKeybinds#12]
I have this mod installed (most recent version) I'm using fabric and I have the Fabric API installed.

The instructions mention a "mod menu", but I can't find that anywhere in the settings. What am I missing?

**Comment by kyrptonaught** [comment]
There is a separate mod for fabric called Mod Menu. This adds the classic mod button from forge to the main menu. Here you can find cmdkeybinds, then click the cogwheel to open the in game config
