### ISSUE TITLE
kyrptconfig

### ISSUE THREAD

**Issue by fantahund** [kyrptonaught/CMDKeybinds#13]
Can you publish kyrptconfig on git?
I would like to update CMDKeybinds to 1.17.

**Comment by kyrptonaught** [comment]
I do plan on updating al of my mods to 1.17 this coming weekend, including kyrptconfig and cmdkeybinds. I definitely can get it up on git too. I was last in the process of adding my own config GUI lib to kyrptconfig rather than using cloth config. I was planning on publishing it then anyway

**Comment by kyrptonaught** [comment]
Updated to 1.17

**Comment by fantahund** [comment]
Hey it's me again. Weren't you planning to publish your config API on git ? :>

**Comment by kyrptonaught** [comment]
Oh hey! I technically did technically get it on GitHub, just in a private repo and forgot to link it to you :p 

Anyways, kyrptconfig is ported to 1.18 and I believe the 1.17 branch of cmdkeybinds is already using the newer in house config screen impl in kyrptconfig. So I think the 1.18 port will be as simply as dep bumps

**Comment by kyrptonaught** [comment]
https://github.com/kyrptonaught/kyrptconfig

**Comment by fantahund** [comment]
Hey you can only share private projects by entering the people who are allowed to see it. :D
