### ISSUE TITLE
Not possible to download the mod through the CurseForge launcher, as well as in the ModPack

### ISSUE THREAD

**Issue by Disguys** [kyrptonaught/CMDKeybinds#14]
Hello, I ran into a problem, I am developing my modpack on Fabric 1.17.1, after I try to export your mod, it does not skip it in the manifest.json, and when exporting to in the .zip file with your mod, the CurseForge site rejected it out for me automatically.
I really like your mod.
Screenshot:
![image](https://user-images.githubusercontent.com/60795989/130534129-cc091c5b-7d32-47ec-becc-da58c163d394.png)

**Comment by kyrptonaught** [comment]
Im not sure what is causing this. Maybe because the mod inst marked as compatible with 1.17.1? I just marked it as so. Maybe give it another shot now?

**Comment by Disguys** [comment]
Everything is working now, thanks.
