### ISSUE TITLE
No longer maps macros to commands in 1.19, instead writes them out as chat text.

### ISSUE THREAD

**Issue by Greg-J** [kyrptonaught/CMDKeybinds#23]
A change was made in 1.19 that breaks the ability to use this for commands. Now it just says the command name instead of using the command.

So instead of Ctrl+C mapping to //copy for WorldEdit like it used to, it just writes "//copy" into chat.

**Comment by kyrptonaught** [comment]
I am working on a full 1.19 release! This has this fixed

**Comment by kyrptonaught** [comment]
The official 1.19 port is out on curseforge
