### ISSUE TITLE
Incompatible with Optifabric

### ISSUE THREAD

**Issue by Sebyx1** [kyrptonaught/CMDKeybinds#25]
[latest.log](https://github.com/kyrptonaught/CMDKeybinds/files/9073443/latest.log)
 Not compatible with Optifabric

 - kyrptconfig 1.4.6-1.19 via cmdkeybind
...
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector spoofDisplayOnlyKeyBinds(Lnet/minecraft/class_304;)Ljava/lang/String; in net.kyrptonaught.kyrptconfig.json:displaykeybind.GameOptionsMixin from mod kyrptconfig failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kyrptconfig-refmap.json

**Comment by lpke** [comment]
I can second this. Happening to me too with `cmdkeybind-1.5.4-1.19` and `optifabric-1.13.5`/`OptiFine_1.19_HD_U_H8`. Have not been able to find a fix.

**Comment by Nova-Plus** [comment]
i can third this. the 2 mods cant be launched together.

**Comment by Nova-Plus** [comment]
i dont mean to rush but is this issue being worked on?

**Comment by kyrptonaught** [comment]
I am taking a look at it. Unfortunately optifine is a horribly invasive mod and is great at making other mod developer's lives miserable. I wish more people would just adopt the alternatives. I can't even find a way to look at their source code accurately. They're using a different patching system other than mixin,

I have keybindings that I don't want to save to the options.txt file. I have a mixin to prevent this. The crash is from my mixin failing to work. Why? Something involving the options saving has been completely flipped by optifine, What is it? No idea, can't read the source code.

**Comment by kyrptonaught** [comment]
I got it, semi painful. Here is a test build. This does have some new features not present in 1.5.4. This may crash with some of my other mods
[cmdkeybind-1.6.0-1.19 PRERELEASE.zip](https://github.com/kyrptonaught/CMDKeybinds/files/9129876/cmdkeybind-1.6.0-1.19.PRERELEASE.zip)

**Comment by Sebyx1** [comment]
> I got it, semi painful. Here is a test build. This does have some new features not present in 1.5.4. This may crash with some of my other mods [cmdkeybind-1.6.0-1.19 PRERELEASE.zip](https://github.com/kyrptonaught/CMDKeybinds/files/9129876/cmdkeybind-1.6.0-1.19.PRERELEASE.zip)

Thx for update this works.
