### ISSUE TITLE
1.19 version doesnt run on 1.19.1

### ISSUE THREAD

**Issue by Mission00i** [kyrptonaught/CMDKeybinds#27]
Not sure if anyone has reported this but for me the game just crashes when trying to load the 1.19 version on 1.19.1. Not sure if you have been looking to update or not so thought id post.

**The error I get is:**
The game crashed whilst unexpected error Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_44099(java.lang.String)' Exit Code: -1

**Comment by Mission00i** [comment]
[crash-2022-08-02_18.24.28-client.txt](https://github.com/kyrptonaught/CMDKeybinds/files/9244430/crash-2022-08-02_18.24.28-client.txt)
Crash Report Attached

**Comment by tomhula** [comment]
Same for me

**Comment by cwshields** [comment]
This is the full report of the crash I get:
https://pastebin.com/nG5RcDSe

**Comment by kyrptonaught** [comment]
1.6.0-1.19.X was released with 1.19.1/1.19.2 support.

**Comment by mirok672** [comment]
Просто скачайте более новую версию мода, он обновился, теперь всё работает.
