### ISSUE TITLE
[Feature Request] Set cooldown time on repeat command

### ISSUE THREAD

**Issue by BlueDeer233** [kyrptonaught/CMDKeybinds#28]
Some servers may kick you out for sending commands too frequently

**Comment by kyrptonaught** [comment]
The repeating macro does allow you to specify the delay

**Comment by BlueDeer233** [comment]
Thanks~ But this mod seems to only work in the foreground. Can you make it work in the case when I ungrab my cursor?

**Comment by kyrptonaught** [comment]
Do you have pause on lost focus disabled? I believe it's F3+P? If so, there's a possibility that keyboards events no longer get sent to mc when not focused

**Comment by BlueDeer233** [comment]
I'm playing on a multiplayer server and F3+P doesn't make it work :(

**Comment by BlueDeer233** [comment]
Thanks a lot~ F3 + P and alt + tab will make it work :)
