### ISSUE TITLE
Request: Allow modifier keys for shortcuts

### ISSUE THREAD

**Issue by cwshields** [kyrptonaught/CMDKeybinds#30]
This would really open up the keyboard for a lot more command shortcuts, especially if you use a lot of mods.

e.g CTRL+T, Shift + X

**Comment by kyrptonaught** [comment]
Macros already have the option for modifier keys. These can be set to any key, including ctrl or shift

**Comment by cwshields** [comment]
Oh, my mistake. I see it right below the option to set the macro key. Thanks!
