### ISSUE TITLE
1.20 Bug Gui

### ISSUE THREAD

**Issue by Luke2206** [kyrptonaught/CMDKeybinds#48]
The mod works in version 1.20.1. 
However, when I want to open the macro gui, only an empty field appears.

Macros created in a previous MC version are saved and I can still use them. But I cannot create a new one.
![image](https://github.com/kyrptonaught/CMDKeybinds/assets/102369468/772ceb61-a711-4e25-9c0c-57e10560615b)

**Comment by kyrptonaught** [comment]
Update out now
