### ISSUE TITLE
Fabric 1.20.4

### ISSUE THREAD

**Issue by Leahcimkrob** [kyrptonaught/CMDKeybinds#59]
Please add support for MC 1.20.4 (fabric)

**Comment by ghost** [comment]
@kyrptonaught Any updates?

**Comment by kyrptonaught** [comment]
Updating of my public mods has mostly come to a halt, I've been doing this for a while and the new frequent breaking changes mojang has been doing has been the final nail in the coffin. I'll still update them to new MCs when I can get around to it.

Also this mod was in the middle of a rewrite allowing for more advanced macros and the ability for them to trigger from actions other than just keybinds. That is not complete, and no idea if I'll get around to it.

For now I've released a 1.20.4 port.
